// animations.js - 视觉效果（TechHub Pro v6.0 正式版）
(function (global) {
  'use strict';
  function initParticles() { var c=document.getElementById('bg-canvas');if(!c||!c.getContext)return;var ctx=c.getContext('2d');var w,h,pts=[];function resize(){w=c.width=c.offsetWidth;h=c.height=c.offsetHeight;}resize();for(var i=0;i<70;i++)pts.push({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.6+0.4,dx:(Math.random()-0.5)*0.3,dy:(Math.random()-0.5)*0.3});var mx=-1,my=-1;c.addEventListener('mousemove',function(e){var r=c.getBoundingClientRect();mx=e.clientX-r.left;my=e.clientY-r.top;});function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(7,193,96,0.5)';for(var i=0;i<pts.length;i++){var p=pts[i];p.x+=p.dx;p.y+=p.dy;if(p.x<0||p.x>w)p.dx*=-1;if(p.y<0||p.y>h)p.dy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='rgba(7,193,96,0.08)';for(var i=0;i<pts.length;i++){for(var j=i+1;j<pts.length;j++){var dx=pts[i].x-pts[j].x,dy=pts[i].y-pts[j].y,d=dx*dx+dy*dy;if(d<130*130){ctx.beginPath();ctx.moveTo(pts[i].x,pts[i].y);ctx.lineTo(pts[j].x,pts[j].y);ctx.stroke();}}}if(mx>=0){for(var i=0;i<pts.length;i++){var dx=pts[i].x-mx,dy=pts[i].y-my,dist=Math.sqrt(dx*dx+dy*dy);if(dist<120){ctx.strokeStyle='rgba(7,193,96,0.25)';ctx.beginPath();ctx.moveTo(pts[i].x,pts[i].y);ctx.lineTo(mx,my);ctx.stroke();}}}requestAnimationFrame(draw);}draw();window.addEventListener('resize',resize);}
  function initTilt() { var cards=document.querySelectorAll('.course-card');cards.forEach(function(card){card.addEventListener('mousemove',function(e){var r=card.getBoundingClientRect();var x=(e.clientX-r.left)/r.width-0.5,y=(e.clientY-r.top)/r.height-0.5;card.style.transform='perspective(800px) rotateX('+(-y*4).toFixed(2)+'deg) rotateY('+(x*5).toFixed(2)+'deg) translateY(-4px)';});card.addEventListener('mouseleave',function(){card.style.transform='';});});}
  function initCursorGlow() { var d=document.createElement('div');d.className='cursor-glow';document.body.appendChild(d);document.addEventListener('mousemove',function(e){d.style.left=e.clientX+'px';d.style.top=e.clientY+'px';});}
  function numberGrow(el,to,dur){var start=0,step=Math.max(1,Math.ceil(to/40)),t=setInterval(function(){start+=step;if(start>=to){start=to;clearInterval(t);}el.textContent=(to>=100?start+'%':start);},dur||30);}
  global.TechHubFX={initParticles:initParticles,initTilt:initTilt,initCursorGlow:initCursorGlow,numberGrow:numberGrow};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){initParticles();initTilt();initCursorGlow();});else{initParticles();initTilt();initCursorGlow();}
})(typeof window!=='undefined'?window:globalThis);
