// DataStore.java - 静态数据访问层（Java 11 兼容，无外部 JSON 依赖，手写 JSON 字符串）
import java.util.ArrayList;
import java.util.List;

public class DataStore {
    // 课程数据以内嵌方式提供（与前端 data.js 保持一致：200 门，价格 9.9~19.9，全部付费）
    // 此处仅返回少量示例课程 + 数据库 courses 表数据；前端以 data.js 为准渲染
    public static List<Object> getCourses() { return new ArrayList<Object>(); } // 由 CourseService.seedIfEmpty 通过内嵌数据填充

    public static String coursesToJson() {
        StringBuilder sb = new StringBuilder();
        sb.append("{\"courses\":[");
        // 从数据库读取
        try { java.sql.ResultSet rs = DatabaseUtil.query("SELECT * FROM courses ORDER BY id LIMIT 500"); boolean first = true; while (rs.next()) { if (!first) sb.append(","); first = false; sb.append("{"); sb.append("\"id\":").append(rs.getInt("id")); sb.append(",\"title\":").append(q(rs.getString("title"))); sb.append(",\"category\":").append(q(rs.getString("category"))); sb.append(",\"price\":").append(rs.getDouble("price")); sb.append(",\"rating\":").append(rs.getDouble("rating")); sb.append(",\"students\":").append(q(rs.getString("students"))); sb.append(",\"teacher\":").append(q(rs.getString("teacher"))); sb.append(",\"platform\":").append(q(rs.getString("platform"))); sb.append(",\"description\":").append(q(rs.getString("description"))); sb.append(",\"redirectUrl\":").append(q(rs.getString("redirect_url"))); sb.append(",\"bilibiliUrl\":").append(q(rs.getString("bilibili_url"))); sb.append(",\"githubUrl\":").append(q(rs.getString("github_url"))); sb.append(",\"free\":").append(rs.getInt("free") == 1); sb.append("}"); } rs.close(); } catch (Exception ignored) {}
        sb.append("],\"total\":").append(countCourses()).append("}");
        return sb.toString();
    }

    public static String searchCourses(String q) {
        if (q == null) q = "";
        String like = "%" + q.toLowerCase() + "%";
        StringBuilder sb = new StringBuilder(); sb.append("{\"q\":").append(q(like)).append(",\"results\":[");
        try { java.sql.PreparedStatement ps = DatabaseUtil.prepare("SELECT * FROM courses WHERE lower(title) LIKE ? OR lower(category) LIKE ? ORDER BY rating DESC LIMIT 50"); ps.setString(1, like); ps.setString(2, like); java.sql.ResultSet rs = ps.executeQuery(); boolean first = true; while (rs.next()) { if (!first) sb.append(","); first = false; sb.append("{\"id\":").append(rs.getInt("id")).append(",\"title\":").append(q(rs.getString("title"))).append(",\"category\":").append(q(rs.getString("category"))).append(",\"price\":").append(rs.getDouble("price")).append("}"); } rs.close(); ps.close(); } catch (Exception ignored) {}
        sb.append("]}"); return sb.toString();
    }

    public static String statsJson() {
        int total = countCourses(); int free = 0; double avg = 0; try { java.sql.ResultSet rs = DatabaseUtil.query("SELECT COUNT(*) c FROM courses WHERE free=1"); if (rs.next()) free = rs.getInt("c"); rs.close(); java.sql.ResultSet r2 = DatabaseUtil.query("SELECT AVG(rating) a FROM courses"); if (r2.next()) avg = r2.getDouble("a"); r2.close(); } catch (Exception ignored) {}
        StringBuilder sb = new StringBuilder(); sb.append("{\"total\":").append(total).append(",\"free\":").append(free).append(",\"paid\":").append(total - free).append(",\"avgRating\":").append(String.format("%.2f", avg)).append("}"); return sb.toString();
    }

    public static String resourcesJson() { return "{\"resources\":[{\"id\":1,\"name\":\"MDN Web Docs\",\"url\":\"https://developer.mozilla.org/zh-CN/\",\"desc\":\"Web技术权威文档\",\"badge\":\"必看\"},{\"id\":2,\"name\":\"roadmap.sh\",\"url\":\"https://roadmap.sh/\",\"desc\":\"开发者学习路线图\",\"badge\":\"必看\"},{\"id\":3,\"name\":\"阮一峰博客\",\"url\":\"https://www.ruanyifeng.com/\",\"desc\":\"优质中文技术博客\",\"badge\":\"必看\"},{\"id\":4,\"name\":\"菜鸟教程\",\"url\":\"https://www.runoob.com/\",\"desc\":\"中文编程入门首选\",\"badge\":\"入门\"},{\"id\":5,\"name\":\"freeCodeCamp\",\"url\":\"https://www.freecodecamp.org/\",\"desc\":\"免费编程学习平台\",\"badge\":\"免费\"},{\"id\":6,\"name\":\"Stack Overflow\",\"url\":\"https://stackoverflow.com/\",\"desc\":\"全球最大编程问答社区\",\"badge\":\"必看\"},{\"id\":7,\"name\":\"GitHub Docs\",\"url\":\"https://docs.github.com/\",\"desc\":\"GitHub官方文档\",\"badge\":\"免费\"},{\"id\":8,\"name\":\"Python官方文档\",\"url\":\"https://docs.python.org/zh-cn/\",\"desc\":\"Python标准库文档\",\"badge\":\"免费\"},{\"id\":9,\"name\":\"Docker官方文档\",\"url\":\"https://docs.docker.com/\",\"desc\":\"容器化技术官方指南\",\"badge\":\"免费\"},{\"id\":10,\"name\":\"Kubernetes官方文档\",\"url\":\"https://kubernetes.io/docs/\",\"desc\":\"K8s官方学习路径\",\"badge\":\"免费\"},{\"id\":11,\"name\":\"LeetCode\",\"url\":\"https://leetcode.cn/\",\"desc\":\"算法刷题平台\",\"badge\":\"面试\"},{\"id\":12,\"name\":\"W3Schools\",\"url\":\"https://www.w3schools.com/\",\"desc\":\"老牌Web技术教程\",\"badge\":\"免费\"}]}"; }
    public static String rankingsJson() { return "{\"rankings\":[{\"rank\":1,\"name\":\"Python\",\"score\":98,\"desc\":\"AI/ML时代第一语言\",\"url\":\"https://www.python.org/\"},{\"rank\":2,\"name\":\"AI/大模型开发\",\"score\":97,\"desc\":\"2026最热方向薪资天花板\",\"url\":\"https://huggingface.co/\"},{\"rank\":3,\"name\":\"JavaScript/TS\",\"score\":95,\"desc\":\"Web开发不可替代\",\"url\":\"https://developer.mozilla.org/zh-CN/docs/Web/JavaScript\"},{\"rank\":4,\"name\":\"系统设计能力\",\"score\":93,\"desc\":\"从码农到架构师必经之路\",\"url\":\"https://github.com/donnemartin/system-design-primer\"},{\"rank\":5,\"name\":\"Java/Spring\",\"score\":92,\"desc\":\"企业级开发霸主\",\"url\":\"https://spring.io/\"},{\"rank\":6,\"name\":\"DevOps/云原生\",\"score\":90,\"desc\":\"Docker+K8s+AWS\",\"url\":\"https://kubernetes.io/docs/\"},{\"rank\":7,\"name\":\"React/Vue\",\"score\":89,\"desc\":\"前端就业核心技能\",\"url\":\"https://react.dev/\"},{\"rank\":8,\"name\":\"Go语言\",\"score\":88,\"desc\":\"云原生新星高并发王者\",\"url\":\"https://go.dev/\"},{\"rank\":9,\"name\":\"SQL/数据分析\",\"score\":87,\"desc\":\"数据驱动决策基本功\",\"url\":\"https://www.postgresql.org/docs/\"},{\"rank\":10,\"name\":\"Rust\",\"score\":85,\"desc\":\"内存安全系统编程未来\",\"url\":\"https://www.rust-lang.org/\"}]}"; }
    public static String githubJson() { return "{\"githubRepos\":[{\"id\":1,\"name\":\"freeCodeCamp\",\"fullName\":\"freeCodeCamp/freeCodeCamp\",\"url\":\"https://github.com/freeCodeCamp/freeCodeCamp\",\"stars\":\"400k+\",\"lang\":\"TypeScript\",\"tag\":\"学习\"},{\"id\":2,\"name\":\"system-design-primer\",\"fullName\":\"donnemartin/system-design-primer\",\"url\":\"https://github.com/donnemartin/system-design-primer\",\"stars\":\"280k+\",\"lang\":\"Java\",\"tag\":\"面试\"},{\"id\":3,\"name\":\"awesome\",\"fullName\":\"sindresorhus/awesome\",\"url\":\"https://github.com/sindresorhus/awesome\",\"stars\":\"310k+\",\"lang\":\"Various\",\"tag\":\"资源\"},{\"id\":4,\"name\":\"developer-roadmap\",\"fullName\":\"kamranahmedse/developer-roadmap\",\"url\":\"https://github.com/kamranahmedse/developer-roadmap\",\"stars\":\"290k+\",\"lang\":\"TypeScript\",\"tag\":\"学习\"},{\"id\":5,\"name\":\"build-your-own-x\",\"fullName\":\"codecrafters-io/build-your-own-x\",\"url\":\"https://github.com/codecrafters-io/build-your-own-x\",\"stars\":\"290k+\",\"lang\":\"Various\",\"tag\":\"实践\"},{\"id\":6,\"name\":\"public-apis\",\"fullName\":\"public-apis/public-apis\",\"url\":\"https://github.com/public-apis/public-apis\",\"stars\":\"310k+\",\"lang\":\"Python\",\"tag\":\"资源\"},{\"id\":7,\"name\":\"tech-interview-handbook\",\"fullName\":\"yangshun/tech-interview-handbook\",\"url\":\"https://github.com/yangshun/tech-interview-handbook\",\"stars\":\"115k+\",\"lang\":\"Various\",\"tag\":\"面试\"},{\"id\":8,\"name\":\"clean-code-javascript\",\"fullName\":\"ryanmcdermott/clean-code-javascript\",\"url\":\"https://github.com/ryanmcdermott/clean-code-javascript\",\"stars\":\"90k+\",\"lang\":\"JavaScript\",\"tag\":\"规范\"},{\"id\":9,\"name\":\"kubernetes\",\"fullName\":\"kubernetes/kubernetes\",\"url\":\"https://github.com/kubernetes/kubernetes\",\"stars\":\"109k+\",\"lang\":\"Go\",\"tag\":\"DevOps\"},{\"id\":10,\"name\":\"tensorflow\",\"fullName\":\"tensorflow/tensorflow\",\"url\":\"https://github.com/tensorflow/tensorflow\",\"stars\":\"184k+\",\"lang\":\"C++\",\"tag\":\"AI\"},{\"id\":11,\"name\":\"spring-boot\",\"fullName\":\"spring-projects/spring-boot\",\"url\":\"https://github.com/spring-projects/spring-boot\",\"stars\":\"74k+\",\"lang\":\"Java\",\"tag\":\"后端\"},{\"id\":12,\"name\":\"react\",\"fullName\":\"facebook/react\",\"url\":\"https://github.com/facebook/react\",\"stars\":\"226k+\",\"lang\":\"JavaScript\",\"tag\":\"前端\"}]}"; }
    public static String bilibiliJson() { return "{\"bilibiliVideos\":[{\"id\":1,\"title\":\"Python零基础入门到精通\",\"teacher\":\"小甲鱼\",\"bvid\":\"BV1w4411D7g8\",\"url\":\"https://www.bilibili.com/video/BV1w4411D7g8\",\"plays\":\"580万\",\"danmaku\":\"8.2万\"},{\"id\":2,\"title\":\"C语言程序设计\",\"teacher\":\"浙江大学\",\"bvid\":\"BV1y4411x7oY\",\"url\":\"https://www.bilibili.com/video/BV1y4411x7oY\",\"plays\":\"420万\",\"danmaku\":\"5.6万\"},{\"id\":3,\"title\":\"Java零基础教程\",\"teacher\":\"韩顺平\",\"bvid\":\"BV1fh411y7R8\",\"url\":\"https://www.bilibili.com/video/BV1fh411y7R8\",\"plays\":\"890万\",\"danmaku\":\"12万\"},{\"id\":4,\"title\":\"React全家桶教程\",\"teacher\":\"尚硅谷\",\"bvid\":\"BV1cZ4y1N7tK\",\"url\":\"https://www.bilibili.com/video/BV1cZ4y1N7tK\",\"plays\":\"320万\",\"danmaku\":\"4.8万\"},{\"id\":5,\"title\":\"前端基础全套\",\"teacher\":\"黑马程序员\",\"bvid\":\"BV1p4411Z7L8\",\"url\":\"https://www.bilibili.com/video/BV1p4411Z7L8\",\"plays\":\"650万\",\"danmaku\":\"9.3万\"},{\"id\":6,\"title\":\"数据结构与算法\",\"teacher\":\"王道考研\",\"bvid\":\"BV1b7411N7B7\",\"url\":\"https://www.bilibili.com/video/BV1b7411N7B7\",\"plays\":\"280万\",\"danmaku\":\"3.5万\"},{\"id\":7,\"title\":\"Linux入门到精通\",\"teacher\":\"狂神说Java\",\"bvid\":\"BV1Sv411r7vd\",\"url\":\"https://www.bilibili.com/video/BV1Sv411r7vd\",\"plays\":\"190万\",\"danmaku\":\"2.8万\"},{\"id\":8,\"title\":\"Docker+K8s容器化实战\",\"teacher\":\"尚硅谷\",\"bvid\":\"BV1wW411Z7mY\",\"url\":\"https://www.bilibili.com/video/BV1wW411Z7mY\",\"plays\":\"150万\",\"danmaku\":\"2.1万\"},{\"id\":9,\"title\":\"Python爬虫实战\",\"teacher\":\"崔庆才\",\"bvid\":\"BV1ZJ411p7cZ\",\"url\":\"https://www.bilibili.com/video/BV1ZJ411p7cZ\",\"plays\":\"230万\",\"danmaku\":\"3.2万\"},{\"id\":10,\"title\":\"Spring Boot 3实战\",\"teacher\":\"雷丰阳\",\"bvid\":\"BV1SJ411o7Up\",\"url\":\"https://www.bilibili.com/video/BV1SJ411o7Up\",\"plays\":\"310万\",\"danmaku\":\"4.5万\"},{\"id\":11,\"title\":\"AI大模型应用开发\",\"teacher\":\"李沐\",\"bvid\":\"BV1mW4y1P7Qq\",\"url\":\"https://www.bilibili.com/video/BV1mW4y1P7Qq\",\"plays\":\"180万\",\"danmaku\":\"2.6万\"},{\"id\":12,\"title\":\"Git与GitHub协作\",\"teacher\":\"CodeSheep\",\"bvid\":\"BV1Jt411z7p7\",\"url\":\"https://www.bilibili.com/video/BV1Jt411z7p7\",\"plays\":\"120万\",\"danmaku\":\"1.8万\"}]}"; }
    public static String roadmapsJson() { return "{\"roadmaps\":[{\"id\":1,\"title\":\"前端工程师路线\",\"months\":\"6-9个月\",\"icon\":\"🎨\",\"steps\":[{\"t\":\"基础阶段\",\"d\":\"HTML/CSS/JS+ES6+Git\"},{\"t\":\"框架阶段\",\"d\":\"React/Vue+TS+状态管理\"},{\"t\":\"工程化阶段\",\"d\":\"Vite/Webpack+CI/CD+测试\"},{\"t\":\"架构阶段\",\"d\":\"微前端+性能优化+SSR\"}]},{\"id\":2,\"title\":\"后端工程师路线\",\"months\":\"8-12个月\",\"icon\":\"⚙️\",\"steps\":[{\"t\":\"编程语言\",\"d\":\"Java/Python/Go选一深入\"},{\"t\":\"数据库与缓存\",\"d\":\"MySQL/Redis/MongoDB\"},{\"t\":\"微服务架构\",\"d\":\"Spring Cloud/gRPC/K8s\"},{\"t\":\"高并发分布式\",\"d\":\"消息队列/限流/分库分表\"}]},{\"id\":3,\"title\":\"AI工程师路线\",\"months\":\"9-12个月\",\"icon\":\"🤖\",\"steps\":[{\"t\":\"数学基础\",\"d\":\"线代/概率/微积分\"},{\"t\":\"机器学习\",\"d\":\"Scikit-learn+特征工程\"},{\"t\":\"深度学习\",\"d\":\"PyTorch/CNN/RNN\"},{\"t\":\"大模型应用\",\"d\":\"LLM API+RAG+Agent\"}]},{\"id\":4,\"title\":\"全栈工程师路线\",\"months\":\"10-14个月\",\"icon\":\"🛡️\",\"steps\":[{\"t\":\"前端基础\",\"d\":\"HTML/CSS/JS+React或Vue\"},{\"t\":\"后端开发\",\"d\":\"Node/Python/Java+数据库\"},{\"t\":\"DevOps\",\"d\":\"Docker/K8s/CI-CD/云服务器\"},{\"t\":\"项目实战\",\"d\":\"全栈部署+性能+安全\"}]},{\"id\":5,\"title\":\"云原生架构师路线\",\"months\":\"12-18个月\",\"icon\":\"☁️\",\"steps\":[{\"t\":\"容器化基础\",\"d\":\"Docker/Kubernetes核心\"},{\"t\":\"微服务治理\",\"d\":\"服务网格/Istio/API网关\"},{\"t\":\"可观测性\",\"d\":\"Prometheus/Grafana/ELK\"},{\"t\":\"架构设计\",\"d\":\"高可用/容灾/混沌工程\"}]}]}"; }
    public static String newsJson() { return "{\"techNews\":[{\"id\":1,\"title\":\"OpenAI发布新一代推理模型，代码能力再突破\",\"category\":\"AI\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-01\"},{\"id\":2,\"title\":\"PyTorch 2.5正式发布，训练性能提升30%\",\"category\":\"AI\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-02\"},{\"id\":3,\"title\":\"Spring Boot 3.3新增虚拟线程支持，并发性能翻倍\",\"category\":\"后端\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-03\"},{\"id\":4,\"title\":\"Kubernetes 1.31引入原生Sidecar支持\",\"category\":\"云原生\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-04\"},{\"id\":5,\"title\":\"Vite 6.0发布，冷启动再提速\",\"category\":\"前端\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-05\"},{\"id\":6,\"title\":\"Chrome 130默认启用CSS锚点定位\",\"category\":\"前端\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-06\"},{\"id\":7,\"title\":\"Node.js 22 LTS发布，内置SQLite模块\",\"category\":\"后端\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-07\"},{\"id\":8,\"title\":\"Python 3.13带来实验性JIT编译器\",\"category\":\"后端\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-08\"},{\"id\":9,\"title\":\"阿里开源Qwen2.5-72B，中文能力领跑\",\"category\":\"AI\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-09\"},{\"id\":10,\"title\":\"腾讯混元大模型开放API免费额度\",\"category\":\"AI\",\"source\":\"科技媒体\",\"url\":\"#news\",\"date\":\"2026-08-10\"}]}"; }

    private static int countCourses() { try { java.sql.ResultSet rs = DatabaseUtil.query("SELECT COUNT(*) c FROM courses"); if (rs.next()) { int n = rs.getInt("c"); rs.close(); return n; } rs.close(); } catch (Exception ignored) {} return 0; }
    private static String q(String s) { if (s == null) return "\"\""; StringBuilder b = new StringBuilder("\""); for (char c : s.toCharArray()) { if (c == '\"') b.append("\\\""); else if (c == '\\') b.append("\\\\"); else if (c == '\n') b.append("\\n"); else if (c == '\r') b.append("\\r"); else b.append(c); } return b.append("\"").toString(); }
}
